# Generated by Django 4.2.2 on 2023-06-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='seniority',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Medium', 'Medium'), ('Senior', 'Senior')], default='Junior', max_length=10),
            preserve_default=False,
        ),
    ]
