# Generated by Django 4.2.2 on 2023-06-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_employee_seniority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name', '-last_name')},
        ),
    ]
