# Generated by Django 4.2.2 on 2023-06-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('pk',)},
        ),
    ]
