# Generated by Django 4.2.2 on 2023-06-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_department_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
